//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type
    {
        public Material_type()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int ID { get; set; }
        public string material_type1 { get; set; }
        public Nullable<double> defective_material_percent { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
