//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class New_TechnologiesEntities : DbContext
    {
        public New_TechnologiesEntities()
            : base("name=New_TechnologiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type> Material_type { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<Partner_products_request> Partner_products_request { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Partners_types> Partners_types { get; set; }
        public DbSet<Product_types> Product_types { get; set; }
        public DbSet<Products_import> Products_import { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Units_of_measurement> Units_of_measurement { get; set; }
    }
}
