//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_request
    {
        public int ID { get; set; }
        public Nullable<int> prodcut { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> product_quantity { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products_import Products_import { get; set; }
    }
}
