//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_types
    {
        public Partners_types()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
