//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_types
    {
        public Product_types()
        {
            this.Products_import = new HashSet<Products_import>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> product_type_coefficient { get; set; }
    
        public virtual ICollection<Products_import> Products_import { get; set; }
    }
}
